services:
  db:
    image: postgres:14.4
    container_name: bills_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
